const SUCCESS = 200

const MOVED_PERMANENTLY = 301
const MOVED_TEMPORARILY = 302

const MALFORMED_REQUEST = 400
const NOT_AUTHORIZED = 401
const NOT_FOUND = 404
const METHOD_NOT_SUPPORTED = 405
const TIMEOUT = 408
const CONFLICT = 409
const LIMIT_RATE = 429

module.exports = {
    SUCCESS,
    MOVED_PERMANENTLY,
    MOVED_TEMPORARILY,
    MALFORMED_REQUEST,
    NOT_AUTHORIZED,
    NOT_FOUND,
    METHOD_NOT_SUPPORTED,
    TIMEOUT,
    CONFLICT,
    LIMIT_RATE,
}